"""
Enhanced mesh export utilities for SF3D with OBJ+MTL generation
Generates both GLB and Wavefront OBJ formats with proper material files
"""

import os
import numpy as np
import trimesh
from typing import List, Optional, Tuple
from pathlib import Path


def generate_mtl_file(
    material_name: str,
    texture_path: str,
    output_path: str,
    roughness: float = 0.5,
    metallic: float = 0.0,
    normal_path: Optional[str] = None
) -> str:
    """
    Generate MTL material file for OBJ mesh
    
    Args:
        material_name: Name of the material
        texture_path: Path to diffuse/albedo texture
        output_path: Path to save MTL file
        roughness: Roughness value (0-1)
        metallic: Metallic value (0-1)
        normal_path: Optional path to normal map
    
    Returns:
        Path to generated MTL file
    """
    mtl_content = f"""# Material file generated by SF3D
# Material: {material_name}

newmtl {material_name}
Ka 1.000 1.000 1.000    # Ambient color (white)
Kd 1.000 1.000 1.000    # Diffuse color (white - comes from texture)
Ks 0.500 0.500 0.500    # Specular color (medium gray)
Ns 32.000                # Specular exponent/shininess
d 1.000                  # Alpha/dissolve (opaque)
Tr 0.000                 # Transparency (inverse of d)
illum 2                  # Illumination model (2 = highlight + diffuse)

# Texture maps
map_Kd {os.path.basename(texture_path)}    # Diffuse/albedo texture
"""

    # Add normal map if provided
    if normal_path and os.path.exists(normal_path):
        mtl_content += f"map_Bump {os.path.basename(normal_path)}    # Normal map\n"
    
    # Add roughness/metallic if supported (non-standard but some viewers support)
    if roughness is not None:
        mtl_content += f"# Roughness: {roughness:.3f}\n"
    if metallic is not None:
        mtl_content += f"# Metallic: {metallic:.3f}\n"
    
    with open(output_path, 'w') as f:
        f.write(mtl_content)
    
    return output_path


def export_obj_with_mtl(
    mesh: trimesh.Trimesh,
    output_path: str,
    texture_name: str = "texture.png",
    material_name: str = "sf3d_material"
) -> Tuple[str, str, str]:
    """
    Export mesh as OBJ with MTL material file and textures
    
    Args:
        mesh: Trimesh object with texture coordinates and materials
        output_path: Base output path (without extension)
        texture_name: Name for texture files
        material_name: Name for material
    
    Returns:
        Tuple of (obj_path, mtl_path, texture_path)
    """
    obj_path = f"{output_path}.obj"
    mtl_path = f"{output_path}.mtl"
    texture_path = f"{output_path}_{texture_name}"
    
    # Extract material properties from the mesh
    base_color_texture = None
    normal_texture = None
    roughness = 0.5
    metallic = 0.0
    
    if hasattr(mesh.visual, 'material') and mesh.visual.material:
        material = mesh.visual.material
        
        # Extract base color texture
        if hasattr(material, 'baseColorTexture') and material.baseColorTexture:
            base_color_texture = material.baseColorTexture
            # Save the texture
            if hasattr(base_color_texture, 'save'):
                base_color_texture.save(texture_path)
        
        # Extract normal texture
        if hasattr(material, 'normalTexture') and material.normalTexture:
            normal_texture = material.normalTexture
            normal_path = f"{output_path}_normal.png"
            if hasattr(normal_texture, 'save'):
                normal_texture.save(normal_path)
        else:
            normal_path = None
        
        # Extract material properties
        if hasattr(material, 'roughnessFactor'):
            roughness = material.roughnessFactor
        if hasattr(material, 'metallicFactor'):
            metallic = material.metallicFactor
    
    # Generate MTL file
    if base_color_texture:
        generate_mtl_file(
            material_name=material_name,
            texture_path=texture_path,
            output_path=mtl_path,
            roughness=roughness,
            metallic=metallic,
            normal_path=f"{output_path}_normal.png" if normal_texture else None
        )
    
    # Export OBJ with material reference
    obj_options = {
        'write_texture': True,
        'include_color': False,  # Use texture instead of vertex colors
        'include_normals': True,
        'include_texture': True
    }
    
    # Custom OBJ export to ensure MTL reference
    with open(obj_path, 'w') as f:
        f.write(f"# OBJ file generated by SF3D\n")
        f.write(f"# Material library: {os.path.basename(mtl_path)}\n")
        f.write(f"mtllib {os.path.basename(mtl_path)}\n\n")
        
        # Write vertices
        for vertex in mesh.vertices:
            f.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        
        # Write texture coordinates
        if hasattr(mesh.visual, 'uv') and mesh.visual.uv is not None:
            for uv in mesh.visual.uv:
                f.write(f"vt {uv[0]:.6f} {1.0 - uv[1]:.6f}\n")  # Flip Y for OBJ convention
        
        # Write normals
        if hasattr(mesh.visual, 'vertex_normals') and mesh.visual.vertex_normals is not None:
            for normal in mesh.visual.vertex_normals:
                f.write(f"vn {normal[0]:.6f} {normal[1]:.6f} {normal[2]:.6f}\n")
        
        f.write(f"\nusemtl {material_name}\n")
        
        # Write faces
        for i, face in enumerate(mesh.faces):
            if hasattr(mesh.visual, 'uv') and mesh.visual.uv is not None:
                if hasattr(mesh.visual, 'vertex_normals') and mesh.visual.vertex_normals is not None:
                    # v/vt/vn format
                    f.write(f"f {face[0]+1}/{i*3+1}/{face[0]+1} {face[1]+1}/{i*3+2}/{face[1]+1} {face[2]+1}/{i*3+3}/{face[2]+1}\n")
                else:
                    # v/vt format
                    f.write(f"f {face[0]+1}/{i*3+1} {face[1]+1}/{i*3+2} {face[2]+1}/{i*3+3}\n")
            else:
                if hasattr(mesh.visual, 'vertex_normals') and mesh.visual.vertex_normals is not None:
                    # v//vn format
                    f.write(f"f {face[0]+1}//{face[0]+1} {face[1]+1}//{face[1]+1} {face[2]+1}//{face[2]+1}\n")
                else:
                    # v format only
                    f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
    
    return obj_path, mtl_path, texture_path


def export_mesh_comprehensive(
    mesh: trimesh.Trimesh,
    output_path: str,
    export_formats: List[str] = ["glb", "obj"],
    texture_name: str = "texture.png",
    material_name: str = "sf3d_material"
) -> dict:
    """
    Export mesh in multiple formats with proper materials
    
    Args:
        mesh: Trimesh object with texture coordinates and materials
        output_path: Base output path (without extension)
        export_formats: List of formats to export ("glb", "obj")
        texture_name: Name for texture files
        material_name: Name for material
    
    Returns:
        Dictionary with paths to exported files
    """
    exported_files = {}
    
    # Export GLB (with embedded textures)
    if "glb" in export_formats:
        glb_path = f"{output_path}.glb"
        mesh.export(glb_path, include_normals=True)
        exported_files["glb"] = glb_path
        print(f"✓ Exported GLB: {glb_path}")
    
    # Export OBJ with MTL
    if "obj" in export_formats:
        try:
            obj_path, mtl_path, tex_path = export_obj_with_mtl(
                mesh=mesh,
                output_path=output_path,
                texture_name=texture_name,
                material_name=material_name
            )
            exported_files["obj"] = obj_path
            exported_files["mtl"] = mtl_path
            exported_files["texture"] = tex_path
            print(f"✓ Exported OBJ: {obj_path}")
            print(f"✓ Exported MTL: {mtl_path}")
            print(f"✓ Exported Texture: {tex_path}")
        except Exception as e:
            print(f"⚠ OBJ export failed: {e}")
    
    return exported_files


def validate_exported_files(file_paths: dict) -> bool:
    """
    Validate that all exported files exist and have reasonable sizes
    
    Args:
        file_paths: Dictionary of file paths from export_mesh_comprehensive
    
    Returns:
        True if all files are valid, False otherwise
    """
    all_valid = True
    
    for file_type, file_path in file_paths.items():
        if not os.path.exists(file_path):
            print(f"❌ {file_type.upper()} file missing: {file_path}")
            all_valid = False
        else:
            size = os.path.getsize(file_path)
            if size == 0:
                print(f"❌ {file_type.upper()} file empty: {file_path}")
                all_valid = False
            else:
                print(f"✓ {file_type.upper()} file valid: {file_path} ({size:,} bytes)")
    
    return all_valid
